#!/usr/bin/env bash
#
# Script to manage the lifecycle of this configuration module.
# Run it without arguments for further information.

MODULE=bash

function INSTALL() {
    local _file=.${MODULE}rc
    local _file_git_prompt=.git-prompt-colors.sh
    link $CURRENT_DIRECTORY/$_file ~/$_file
    link $CURRENT_DIRECTORY ~/.$MODULE
    link $CURRENT_DIRECTORY/$_file_git_prompt ~/$_file_git_prompt
    setupSubmodules
}

############################################################## begin-bootstrap
function _bootstrap() {
    CURRENT_DIRECTORY=$(dirname $(readlink -e $0))
    local _libDirectory=configuration-module-lib
    local _template=$CURRENT_DIRECTORY/$_libDirectory/management-template.sh
    command -v git &>/dev/null && {
        cd $CURRENT_DIRECTORY
        git submodule --quiet update --init $_libDirectory
        [ -e $_template ] && source $_template $@
    }
    echo "Bootstrap operation failed. Aborting."; exit 1
}
_bootstrap $@
############################################################## end-bootstrap
