#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

xCursorColor=$(xrdb -query | grep -e URxvt.cursorColor | cut -f 2)

function translateInVT100ColorCode() {

    case $1 in
         0 )
            echo '\[\e[30m\]' ;;
         1 )
            echo '\[\e[31m\]' ;;
         2 )
            echo '\[\e[32m\]' ;;
         3 )
            echo '\[\e[33m\]' ;;
         4 )
            echo '\[\e[34m\]' ;;
         5 )
            echo '\[\e[35m\]' ;;
         6 )
            echo '\[\e[36m\]' ;;
         7 )
            echo '\[\e[37m\]' ;;
         8 )
            echo '\[\e[1;30m\]' ;;
         9 )
            echo '\[\e[1;31m\]' ;;
        10 )
            echo '\[\e[1;32m\]' ;;
        11 )
            echo '\[\e[1;33m\]' ;;
        12 )
            echo '\[\e[1;34m\]' ;;
        13 )
            echo '\[\e[1;35m\]' ;;
        14 )
            echo '\[\e[1;36m\]' ;;
        15 )
            echo '\[\e[1;37m\]' ;;
         * )
            echo '' ;;
    esac
}

VT100ColorCode=$(translateInVT100ColorCode $xCursorColor)

# Prompt
PS1="$VT100ColorCode>>\[\e[m\] \u@\h \W\$ "

# History
export HISTSIZE=32768               # Larger bash history (allow 32³ entries; default is 500)
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:ls *:l:ll:h:h *:history:history *:cd:cd -:pwd:exit:date:* --help"
